### ISSUE TITLE
Question about latency

### ISSUE THREAD

**Issue by JH-ninjatech** [xdit-project/mochi-xdit#20]
Hi,

Thnx for sharing this repo. Dioes the latency table reported in README include the module loading time as well? Or is it just the pure sampling time?

**Comment by feifeibear** [comment]
No, the data loading time is not counted! Since in service, we only load mode once.

We have printed the detailed time decomposition on the console. Sampler time dominated, we only present the sampling.

I can show you a timeline on 2 GPUs using cfg parallel.

[36m(MultiGPUContext pid=3331329)[0m Timing load_dit
[36m(MultiGPUContext pid=3331329)[0m Stage                   Time(s)    Percent
[36m(MultiGPUContext pid=3331329)[0m init_process_group         7.13      3.93%
[36m(MultiGPUContext pid=3331329)[0m load_text_encoder         48.05     26.46%
[36m(MultiGPUContext pid=3331329)[0m load_dit                 122.33     67.35%
[36m(MultiGPUContext pid=3331329)[0m load_vae                   4.12      2.27%
[36m(MultiGPUContext pid=3331355)[0m Timing load_vae

[36m(MultiGPUContext pid=3331329)[0m Timing decoding
[36m(MultiGPUContext pid=3331355)[0m Max memory reserved: 35.27 GB
[36m(MultiGPUContext pid=3331355)[0m Stage                   Time(s)    Percent
[36m(MultiGPUContext pid=3331355)[0m conditioning               1.35      0.64%
[36m(MultiGPUContext pid=3331355)[0m sampling                 199.07     93.68%
[36m(MultiGPUContext pid=3331355)[0m decoding                  12.09      5.69%
